name: myapp
description: "A Flutter project containing multiple modules."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  sentry_flutter: ^8.0.0

  # State Management
  flutter_riverpod: ^2.4.9
  rxdart: ^0.27.7
  get_it: ^7.6.7

  # Database
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.3
  path: ^1.9.0
  sqlite3: ^2.3.1
  
  # Networking & Services
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1

  # Security & Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  cryptography: ^2.7.0

  # Utilities
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  workmanager: ^0.5.2
  battery_plus: ^5.0.3
  wakelock_plus: ^1.1.4
  convert: ^3.1.1
  collection: ^1.18.0
  queue: ^3.3.0
  archive: ^3.4.10
  synchronized: ^3.1.0+1

  # UI & Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
